### ISSUE TITLE
load up bug

### ISSUE THREAD

**Issue by madtomic** [TfT-02/Ghosts#11]
[21:36:50 INFO]: [Ghosts] Enabling Ghosts v0.0.1-b52
[21:36:51 WARN]: Exception in thread "Thread-7"
[21:36:51 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[21:36:51 WARN]:        at java.lang.String.substring(Unknown Source)
[21:36:51 WARN]:        at net.gravitydevelopment.updater.ghosts.Updater.version Check(Updater.java:432)
[21:36:51 WARN]:        at net.gravitydevelopment.updater.ghosts.Updater.access$ 400(Updater.java:49)
[21:36:51 WARN]:        at net.gravitydevelopment.updater.ghosts.Updater$UpdateR unnable.run(Updater.java:540)
[21:36:51 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by madtomic** [comment]
It don't effect the plugin but it comes up every time the server is loaded.
